### ISSUE TITLE
Rust: implement FromStr for Register

### ISSUE THREAD

**Issue by tnballo** [icedland/iced#136]
Hey! Thanks for writing a fantastic disassembler.

I'd like to convert user-provided strings to register enums in a [CLI tool](https://github.com/entropic-security/xgadget) that uses the Rust library. Supporting this functionality might be useful for other purposes down the line, like #77.

AFAIK there are two ways to do this (both adding a optional dependencies gated by the `std` feature):
- The simplest is to use the [`strum` crate's `EnumString`](https://docs.rs/strum/0.20.0/strum/derive.EnumString.html) macro.
- I think a better fit here would be a combo of [`num-traits` crate's `FromPrimitive`](https://docs.rs/num-traits/0.2.14/num_traits/cast/trait.FromPrimitive.html) and using the existing `GEN_DEBUG_REGISTER` array. This approach gains both `String` -> `Register` and `u32`/`u64`/`usize`, etc -> `Register`.

I've tried out the latter in [this commit to my fork](https://github.com/tnballo/iced/commit/19ca3470e8ed4e2fd7abfb32ceffdb421b9e819f) (without updating the generator code, which I assume is a pre-req to PR-ing).

Please let me know what you think!

**Comment by tnballo** [comment]
Actually, a 3rd option here might be having the generator spit out something like:

```
impl Register {
    fn from_usize(val: usize) -> Self {
        match val {
            0 => Register::None,
            1 => Register::AL,
            2 => Register::CL,
            // ...
            248 => Register::TMM7,
            _ => panic!("Bad register value: {}", val),
        }
    }
}
```
This wouldn't require additional dependencies, because it would take the place of `FromPrimitive` mentioned above.

**Comment by 0xd4d** [comment]
I think a better solution would be to add a `Register` iterator (a `Register` associated function) that would return all enum values.

The caller can then iterate over them and create a hash table `format!("{:?}", enum_value)` -> `Register`.

Since the user creates the hash table, they can also decide if the string key should be case sensitive or not.

eg.

```Rust
impl Register {
	pub fn values() -> iterator_type_here {
		// ...
	}
}
```

The iterator impl would iterate from `0..IcedConstants::REGISTER_ENUM_COUNT` and use transmute to convert it (it's safe since all values are valid).
