### ISSUE TITLE
Omitting RIP where possible

### ISSUE THREAD

**Issue by MeFisto94** [icedland/iced#171]
When allocating memory, one typically needs to have a rough idea for the size required, but in order to estimate the size, one needs to assemble already, requiring the RIP, which would be the location of the freshly allocated memory, thus building a "circular dependency"

In other words: I'd like to assemble everything without specifying a RIP (that means all addresses being used absolute, labels being used relative), effectively creating relocatable code, so that they can be placed on every memory address returned by the allocator.

First assemblying using RIP = 0, allocating a code cave and then re-assembling is also unreliable, because the assembly size may change based on RIP being too far away for relative instructions etc.

Is there a way to sanely achieve this already?
Would making the RIP optional even make sense?
Would it be useful to add such a situation to the examples?

Realistically I guess one could do the assemble-twice approach and plan for some overhead size.

Thanks in Advance!

**Comment by wtfsck** [comment]
> Realistically I guess one could do the assemble-twice approach and plan for some overhead size.

This would be the easiest thing to do. Just pick an IP close to the expected memory location (or 0 if you don't know), encode the instructions to get N (size of code). Allocate N bytes and re-encode using the now known address. Most likely the new size will equal N but could in theory be bigger. To handle that you could allocate eg. 1.2*N bytes.

RIP can't be optional since it's needed when encoding all RIP relative instructions (eg. `Jcc/JMP rel` and `[rip+xxx]`)
