### ISSUE TITLE
Memory displacement reencoding inconsistency

### ISSUE THREAD

**Issue by paulfariello** [icedland/iced#179]
Using iced_x86 py module version 1.12.

Decoding `mov [rbx+rax-8],rdx` and trying to create another instruction with same memory operand lead to the following error:

```
OverflowError: Python int too large to convert to C long
```

In fact, memory displacement is `fffffffffffffff8: u64` as returned by `instruction.memory_displacement` but `MemoryOperand` expect `i64`.

One could reproduce the issue with the following script:

```
import iced_x86

raw = b"\x48\x89\x54\x03\xF8"

decoder = iced_x86.Decoder(64, raw, ip=0x00)
instr = next(decoder)
print(instr)

iced_x86.Instruction.create_reg_mem(
    iced_x86.Code.LEA_R64_M,
    iced_x86.Register.RAX,
    iced_x86.MemoryOperand(
        base=instr.memory_base,
        index=instr.memory_index,
        displ=instr.memory_displacement,
        displ_size=instr.memory_displ_size,
        seg=instr.memory_segment,
    ),
)
```

**Comment by wtfsck** [comment]
I've created a new static method called `ctor_u64()` that you can call instead of the ctor, eg. `iced_x86.MemoryOperand.ctor_u64(...)`. Ideally the ctor should be able to handle both `i64` and `u64` input but there seems to be some limitation in the `pyo3` lib I use and I couldn't get it to work when the arg also has a default value (`0` in this case).

I'll see if it's possible to fix this in the future but for now, use `ctor_u64()` if you know it's unsigned.

Another workaround is to convert it to a signed value like so:

```python
def si(v: int) -> int:
    if (v & 0x8000_0000_0000_0000):
        # It's the same as -(-v) but it won't work since v is unsigned
        return -((~v & 0xFFFF_FFFF_FFFF_FFFF) + 1)
    return v

i = 0xFFFF_FFFF_FFFF_FFFF
print(f"i = {i}")
print(f"si(i) = {si(i)}")
```

You can compile the wheel yourself or update to `1.13.0` after the CI has built it and pushed it to PyPI. Build instructions is in the [README](https://github.com/icedland/iced/blob/master/src/rust/iced-x86-py/README.md)
