### ISSUE TITLE
Distinguishing end-of-input from invalid instruction

### ISSUE THREAD

**Issue by blitz** [icedland/iced#195]
`Decoder::decode` currently returns `Code::INVALID` for two different cases:

- We're out of bytes to decode,
- The instruction is invalid.

I'm currently trying to use iced in a VMM and this is very inconvenient, because it is not clear how many bytes to fetch from the guest. Blindly fetching 15 bytes (longest possible instruction) is problematic, because this means we fetch more bytes than we need to and this will result in injecting unexpected page faults in the guest.

Do you have any suggestions how to reliably differentiate between the two above conditions?

**Comment by wtfsck** [comment]
Yes, you can call `last_error()` to get why it failed to decode.

If it's `InvalidInstruction`, iced managed to read all the bytes it needed and it figured out that it's not an instruction or the instruction has an invalid encoding or an invalid prefix, etc.

If it's `NoMoreBytes`, it means that it may or may not be an invalid instruction. iced needs to read more bytes. In this case, you can find the number of bytes it's already decoded in `Instruction::len()`. Since all x86 pages are at least 4KB aligned, you can read less than 15 bytes if you don't want to trigger a possible page fault. If it still returns `NoMoreBytes`, I guess you have to keep reading on the next page.

**Comment by blitz** [comment]
> Yes, you can call Decoder::last_error() to get why it failed to decode.

Ah, didn't see that it's specified there. Thanks!

> Since all x86 pages are at least 4KB aligned, most of the time you should be able to read up to 15 bytes but if you're close to the end of the page, you can read less than 15 bytes if you don't want to trigger a possible page fault. If it still returns NoMoreBytes, I guess you have no choice but to keep reading on the next page.

Yes, that's roughly what I was aiming to implement.

Thanks for the quick clarification!
