### ISSUE TITLE
python iced-x86 typing issue with Register

### ISSUE THREAD

**Issue by paulfariello** [icedland/iced#199]
It would be nice to avoid type error when using register with the iced API.

For exemple the following simple python script raise a type error with mypy:
```python
import iced_x86

iced_x86.RegisterExt.is_gpr(iced_x86.Register.RAX)
```

```bash
$ python -m mypy test.py
test.py:3: error: Argument 1 to "is_gpr" of "RegisterExt" has incompatible type "int"; expected "Register"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by wtfsck** [comment]
I did try to use real Python enums at first but found out that they're incredibly slow. I mean REALLY slow. There's a   CPython PR that should fix that, but I'm not sure if it's been merged yet. Even if it has, it will be in 3.10 and I     have to support older Python versions too.

I ended up using modules and constants. No perf penalty. Fast startup.

The *.pyi file however pretends they're real Python enums so completions in IDEs show the correct arguments (eg.        `Register` instead of `int`).

Possible workarounds:

- Delete `_iced_x86_py.pyi` and/or `py.typed`. You'll probably lose IDE code completion and all docs.
- Generate real Python enums if you don't care about startup perf. The *.pyi file may need to be updated to include     them too. The generator generates them, see `WriteEnumCore()` in `src/csharp/Intel/Generator/Enums/Python/              PythonEnumsGenerator.cs`

**Comment by paulfariello** [comment]
Would have guessed that performances were the issue here. Personally, I wouldn't trade performance for typing.

Maybe faking the type in `Register.py` could hide this issue for API client.
The following test doesn't raise typing error.

```python
from enum import IntEnum

# Not sure Register definition can still be in .pyi file
class Register(IntEnum):
    NONE = 0

# RegisterExt doesn't changes
def base(reg: Register) -> Register:
    return reg

# Register.py doesn't declare int (but still assign int)
# need to ignore type error
rax: Register = 53 # type: ignore

# API usage doesn't raise error
base(rax)
```

**Comment by wtfsck** [comment]
iced-x86 has a module called Register so I'm not sure if that example will work though. Have you tried this when there's a module and an enum with the same name?

**Comment by paulfariello** [comment]
The following structure seems to be working with mypy.

`test.py`
```python
import iced

reg = iced.Register.RAX
iced.RegisterExt.base(reg)
```
`iced/__init__.py`
```python
from ._iced_x86_py import RegisterExt

from . import Register

__all__ = [
	"RegisterExt",
	"Register",
]
```
`iced/_iced_x86_py.pyi`
```python
from enum import IntEnum, IntFlag

class Register(IntEnum):
    NONE = 0
    ...

class RegisterExt:
    @staticmethod
    def base(reg: Register) -> Register:
        ...
```
`iced/Register.py`
```python
from ._iced_x86_py import Register

RAX: Register = 53 # type: ignore

```
It just require to define a real Register class in `_iced_x86_py.so` in order to avoid error at runtime when importing it in `Register.py`.

**Comment by wtfsck** [comment]
That almost works. It fails when you add your own funcs, eg.:

```python
import iced_x86

reg = iced_x86.Register.RAX
iced_x86.RegisterExt.base(reg)

def my_fun(code: iced_x86.Code, reg: iced_x86.Register):
    pass
```

```
iced.py:6: error: Module "iced_x86.Code" is not valid as a type
iced.py:6: error: Module "iced_x86.Register" is not valid as a type
```

**Comment by wtfsck** [comment]
I have a simple fix for that last problem, will push it later.

**Comment by wtfsck** [comment]
It should work now. If you add type annotations to your methods, append an `_` to enums, eg. `reg: Register` -> `reg: Register_`.
