### ISSUE TITLE
Disassembling out of the virtual address space.

### ISSUE THREAD

**Issue by vext01** [icedland/iced#364]
Hi,

Not really an issue, more of a question.

Is there a way to disassemble the instruction stream out of the virtual address of the current process?

AFAICS, iced needs a byte slice of the instruction stream, but [it's difficult to make a slice of the current virtual address space in a UB-free manner](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/get.20a.20slice.20of.20the.20entire.20address.20space.2E/near/314070097).

Has anyone ever explored this?

Thanks

**Comment by wtfsck** [comment]
You could use unsafe code to create a slice. Since it's your own code you want to disassemble, it should be readonly and there should be no &mut slices in that address range, so I don't think it can be UB.

You could also read those bytes (from your process) into some Vec<u8> and then pass that vec to the decoder.

Or you could read your file on disk.

**Comment by vext01** [comment]
Thanks. This confirms that there is no API that I should be using.

**Comment by vext01** [comment]
> Or you could read your file on disk.

BTW, this doesn't work well due to PLT and relocations.
